# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RNAfold_MFE <- function(seq) {
    .Call('_XNAString_RNAfold_MFE', PACKAGE = 'XNAString', seq)
}

RNAcofold_MFE <- function(seq) {
    .Call('_XNAString_RNAcofold_MFE', PACKAGE = 'XNAString', seq)
}

